[package]
authors = ["Ross Harrison <rtharrison86@gmail.com>"]
name = "jot-down"
version = "1.0.0"

[dependencies]
rusqlite = "0.11.0"

[dependencies.clap]
features = ["yaml"]
version = "2.19.0"

[dependencies.uuid]
features = ["v4", "serde"]
version = "0.5"
