[package]
authors = ["Ross Harrison <rtharrison86@gmail.com>"]
name = "jot"
version = "1.0.0"

[dependencies]
bson = "0.7.0"
chrono = "0.3.1"
ejdb = "0.3.0"
mongodb = "0.2.7"
uuid = { version = "0.5", features = ["v4"] }

[dependencies.clap]
features = ["yaml"]
version = "2.19.0"
